#!/bin/sh
# SPDX-License-Identifier: 0BSD
# Copyright (C) 2022 Beckhoff Automation GmbH & Co. KG

set -e
set -u

# root permissions are required to run VMs
if test "$(id -u)" -ne 0; then
	printf "%s must be run as root\n" "${0##*/}"
	exit 1
fi

# Default values for VM configuration
readonly vm_name="samplevm"

# Ensure that kernel modul vmm.ko is loaded
kldload -n vmm.ko

while true; do
	nic="igb1" 
        tap="$(doas ifconfig tap create)"
	bridge="$(doas ifconfig bridge create)"
	doas sysctl net.link.tap.up_on_open=1
	doas ifconfig ${bridge} addm ${tap} addm ${nic} up
	doas sysctl net.link.bridge.pfil_member=0


	# start a simple UEFI based VM instance
	_bhyve_rc=0
	bhyve \
		-A -H -P \
		-c 2 \
		-m 2G \
		-s 0:0,hostbridge \
		-s 1:0,virtio-blk,/dev/zvol/"${vm_disk}" \
		-s 2:0,virtio-net,"${tap}" \
		-s 3:0,virtio-net,"${nettap}" \
		-s 10:0,ahci-cd,"${iso_file}" \
		-l bootrom,/usr/local/share/uefi-firmware/BHYVE_BHF_UEFI.fd,"${efi_vars}" \
		-s 29,fbuf,tcp=0.0.0.0:"${vnc_port}",w=1024,h=768,wait \
		-s 30,xhci,tablet \
		-s 31:0,lpc \
		"${vm_name}"
	_bhyve_rc=$?

	# according to bhyve man pages the return codes indicates
	# how the VM was terminated:
	# 0: rebooted
	# 1: powered off
	if test "${_bhyve_rc}" -ne 0; then
		printf "bhyve exited with return code: %s\n" "${_bhyve_rc}"
		break
	fi
	
	#remove the networking ports
	doas ifconfig ${bridge} deletem ${tap} deletem ${nic}
	doas ifconfig ${bridge} down
	doas ifconfig ${bridge} destroy
	doas ifconfig ${tap} destroy
	
	printf "Restarting %s\n" "${vm_name}"

done
